import { z } from "zod";

export const ExecutionTaskStatusSchema = z.enum([
  "queued",
  "awaiting_approval",
  "running",
  "completed",
  "failed",
  "timed_out",
  "aborted",
  "rejected",
]);

export const ExecutionTaskRecordSchema = z.object({
  taskId: z.string().trim().min(1),
  commandId: z.string().trim().min(1),
  traceId: z.string().trim().min(1).nullable().default(null),
  spanId: z.string().trim().min(1).nullable().default(null),
  parentSpanId: z.string().trim().min(1).nullable().default(null),
  toolCallId: z.string().trim().min(1).nullable().default(null),
  runId: z.string().trim().min(1).nullable().default(null),
  operationalSessionId: z.string().trim().min(1).nullable().default(null),
  projectId: z.string().trim().min(1).nullable().default(null),
  agentId: z.string().trim().min(1).nullable().default(null),
  filePath: z.string().trim().min(1).nullable().default(null),
  diffId: z.string().trim().min(1).nullable().default(null),
  executable: z.string().trim().min(1),
  args: z.array(z.string()).default([]),
  cwd: z.string().trim().min(1),
  env: z.record(z.string()).default({}),
  timeoutMs: z.number().int().positive().nullable().default(null),
  status: ExecutionTaskStatusSchema,
  retryOfTaskId: z.string().trim().min(1).nullable().default(null),
  attempt: z.number().int().positive().default(1),
  approvalRequired: z.boolean().default(false),
  risk: z.enum(["low", "medium", "high"]).default("low"),
  policyReason: z.string().trim().min(1).nullable().default(null),
  approved: z.boolean().default(false),
  approvedBy: z.string().trim().min(1).nullable().default(null),
  approvalReason: z.string().trim().min(1).nullable().default(null),
  processId: z.number().int().positive().nullable().default(null),
  stdoutPath: z.string().trim().min(1),
  stderrPath: z.string().trim().min(1),
  stdoutBytes: z.number().int().nonnegative().default(0),
  stderrBytes: z.number().int().nonnegative().default(0),
  stdoutTail: z.string().default(""),
  stderrTail: z.string().default(""),
  exitCode: z.number().int().nullable().default(null),
  signal: z.string().trim().min(1).nullable().default(null),
  errorMessage: z.string().trim().min(1).nullable().default(null),
  interactivePromptDetected: z.boolean().default(false),
  interactivePromptText: z.string().trim().min(1).nullable().default(null),
  timedOut: z.boolean().default(false),
  startedAt: z.string().datetime(),
  finishedAt: z.string().datetime().nullable().default(null),
  lastOutputAt: z.string().datetime().nullable().default(null),
  durationMs: z.number().int().nonnegative().default(0),
});

export type ExecutionTaskStatus = z.output<typeof ExecutionTaskStatusSchema>;
export type ExecutionTaskRecord = z.output<typeof ExecutionTaskRecordSchema>;
